# Multi-Factor Strategy V1 - Baseline
# Generated by: Gemini 2.5 Pro (adapted for available datasets)
# Date: 2025-10-10
# Strategy: Momentum (40%) + Value (30%) + Quality (30%)

from finlab import data, backtest

# 載入數據集 - 只使用已驗證可用的數據
close = data.get('price:收盤價')
volume = data.get('price:成交股數')
pe_ratio = data.get('price_earning_ratio:本益比')
roe = data.get('fundamental_features:ROE稅後')
revenue_yoy = data.get('monthly_revenue:去年同月增減(%)')

# 基礎篩選條件
turnover = close * volume
liquidity_filter = turnover.average(20) > 150_000_000
price_filter = close > 10
base_condition = liquidity_filter & price_filter

# ====== 因子計算 ======

# 1. 動量因子 (Momentum Factor) - 權重 40%
# 40日價格動量 + 成交量確認
momentum_40d = close.pct_change(40)
volume_trend = volume.average(5) > volume.average(20)
momentum_factor = momentum_40d * volume_trend

# 2. 價值因子 (Value Factor) - 權重 30%
# 改進的P/E策略：結合低P/E與ROE篩選，避免價值陷阱
# 高ROE + 低P/E = 優質價值股
value_factor = (1 / (pe_ratio + 1)) * roe

# 3. 質量因子 (Quality Factor) - 權重 30%
# 結合ROE與營收成長
quality_factor = roe * (revenue_yoy / 100)

# 4. 低波動率因子 (Low Volatility) - 整合到綜合分數
daily_returns = close.pct_change(1)
volatility_40d = daily_returns.rolling(40).std()
low_vol_factor = 1 / volatility_40d

# ====== 因子組合 ======
# 使用 rank() 正規化各因子
momentum_rank = momentum_factor.rank(ascending=True)
value_rank = value_factor.rank(ascending=True)
quality_rank = quality_factor.rank(ascending=True)
low_vol_rank = low_vol_factor.rank(ascending=True)

# 綜合評分（調整權重：強化動量與質量）
final_score = (
    momentum_rank * 0.40 +
    value_rank * 0.25 +
    quality_rank * 0.25 +
    low_vol_rank * 0.10
)

# ====== 選股與回測 ======
position = final_score[base_condition]
position = position.is_largest(10)  # 選前10檔

# 執行回測 - 使用嚴格風控參數
report = backtest.sim(
    position,
    resample="M",
    fee_ratio=1.425/1000/3,
    stop_loss=0.05,      # 5% 停損
    take_profit=0.20,    # 20% 停利
    position_limit=0.08, # 8% 單一持股上限
    name="MultiFactor_Baseline_V1"
)

# 輸出結果
print("=== 多因子策略 V1 基準測試結果 ===")
print(f"年化報酬率: {report.metrics.annual_return():.2%}")
print(f"夏普比率: {report.metrics.sharpe_ratio():.2f}")
print(f"最大回撤: {report.metrics.max_drawdown():.2%}")
print("\n目標指標:")
print(f"  Sharpe Ratio: > 2.0  [當前: {report.metrics.sharpe_ratio():.2f}]")
print(f"  年化報酬率: > 30%   [當前: {report.metrics.annual_return():.2%}]")
print(f"  最大回撤: < -20%    [當前: {report.metrics.max_drawdown():.2%}]")
